services:

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mypostgresqldb
      POSTGRES_USER: userdm
      POSTGRES_PASSWORD: admin@234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userdm"]
      interval: 5s
      timeout: 2s
      retries: 5



  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://userdm:admin@234@db:5432/mypostgresqldb
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: