version: '3'


networks:
  app-tier:
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - "./compose-test/www:/usr/share/nginx/html:ro"
      - "./compose-test/log:/var/log/nginx"
      - "./compose-test/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "127.0.0.1:80:80"
    networks:
      - app-tier

  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    volumes:
      - "./compose-test/postgre:/bitnami/postgresql"
    networks:
      - app-tier
