version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - "./compose-test/www:/usr/share/nginx/html:ro"
      - "./compose-test/log:/var/log/nginx"
      - "./compose-test/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "127.0.0.1:80:80"