
services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: mysqldb
      PGDATABASE: mysqldb

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - appnet

  web:
    build: .
    # ports:
      # - "8000:8000"
    expose:
      - 8000
    volumes:
      - .:/app
      - static:/app/static

    environment:
      - DATABASE_URL=postgres://user:admin%40123@db:5432/mysqldb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/app/static
    depends_on:
      - web
    networks:
      - appnet

volumes:
  postgres_data:
  static:

networks:
  appnet:
    driver: bridge
