
services:

  node:
    build: ./nodejs
    volumes:
      - ./app:/www
    ports:
      - "3000:3000"
    networks:
      - appnet

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mysqldb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - appnet

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://user:admin@123@db:5432/mysqldb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge
