
services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: mysqldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - appnet

  # node:
  #   build: ./nodejs
  #   volumes:
  #     - ./nodejs:/app/www
  #   environment:
  #     DATABASE_URL: postgres://user:admin%40123@db:5432/mysqldb
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - appnet

  web:
    build: .
    # container_name: django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://user:admin%40123@db:5432/mysqldb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge
