services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: mysqldb
      PGDATABASE: mysqldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - appnet

  web:
    build: .
    expose:
      - 8000
    volumes:
      - .:/app
      - static:/app/static
    environment:
      - DATABASE_URL=postgres://user:admin%40123@db:5432/mysqldb
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - appnet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/app/static
      - ./nginx/ssl:/etc/ssl/certs
      - ./nginx/ssl:/etc/ssl/private
    depends_on:
      - web
    networks:
      - appnet

  redis:
    image: redis:latest
    ports:
      - "5001:6379"
    volumes:
      - redis_data:/data
    networks:
      - appnet

volumes:
  postgres_data:
  static:
  redis_data:

networks:
  appnet:
    driver: bridge
