# Generated by Django 5.1.3 on 2025-01-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('icons', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='BlockUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField()),
                ('idBlocked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chans',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('invite_link', models.CharField()),
                ('created', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMaps', models.IntegerField()),
                ('LinkMaps', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchsTournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTournaments', models.IntegerField()),
                ('idMatchs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MultiCasseBrique',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_p1', models.IntegerField()),
                ('id_p2', models.IntegerField()),
                ('score_p1', models.IntegerField()),
                ('score_p2', models.IntegerField()),
                ('date', models.CharField()),
                ('map', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_p1', models.IntegerField()),
                ('id_p2', models.IntegerField()),
                ('score_p1', models.IntegerField()),
                ('score_p2', models.IntegerField()),
                ('date', models.CharField()),
                ('difficulty', models.IntegerField()),
                ('bounce_nb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='soloCasseBrique',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idMap', models.IntegerField()),
                ('score', models.IntegerField()),
                ('date', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTournaments', models.IntegerField()),
                ('date', models.CharField()),
                ('nb_of_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField()),
                ('idAchievement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserChan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idChan', models.IntegerField()),
                ('idUser', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('date', models.CharField()),
                ('image', models.CharField()),
                ('status', models.BooleanField()),
                ('win_nb', models.IntegerField(default=0)),
                ('lose_nb', models.IntegerField(default=0)),
            ],
        ),
    ]
