# Generated by Django 5.1.4 on 2025-03-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casse_brique_room',
            name='map_id',
            field=models.IntegerField(),
        ),
    ]
