# Generated by Django 5.1.4 on 2025-02-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='read',
            field=models.BooleanField(null=True),
        ),
    ]
