# Generated by Django 5.1.4 on 2025-01-31 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multicassebrique',
            name='id_p2',
        ),
        migrations.RemoveField(
            model_name='pong',
            name='id_p2',
        ),
        migrations.AlterField(
            model_name='multicassebrique',
            name='id_p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M_CB_games_as_p2', to='home_sys.users'),
        ),
        migrations.AlterField(
            model_name='pong',
            name='id_p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pong_games_as_p2', to='home_sys.users'),
        ),
    ]
