# Generated by Django 5.1.4 on 2025-02-18 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multicassebrique',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='M_CB_winner', to='home_sys.users'),
            preserve_default=False,
        ),
    ]
