# Generated by Django 5.1.4 on 2025-01-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chans',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
