# Generated by Django 5.1.4 on 2025-01-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solocassebrique',
            name='idPlayer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
