# Generated by Django 5.1.4 on 2025-01-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_chan', models.IntegerField()),
                ('id_u1', models.IntegerField()),
                ('id_u2', models.IntegerField()),
            ],
        ),
    ]
