# Generated by Django 5.1.4 on 2025-01-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='profile_pics/basePP.png', upload_to='profile_pics/'),
        ),
    ]
