# Generated by Django 5.1.3 on 2025-01-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chans',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='multicassebrique',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pong',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solocassebrique',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
