# Generated by Django 5.1.4 on 2025-01-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='idMaps',
        ),
        migrations.AlterField(
            model_name='maps',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
