# Generated by Django 5.1.4 on 2025-03-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0002_alter_casse_brique_room_map_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='logstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
