# Generated by Django 5.1.4 on 2025-01-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0002_alter_chans_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chans',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
