# Generated by Django 5.1.4 on 2025-02-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0002_currentgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_link',
            field=models.BooleanField(default=False),
        ),
    ]
