# Generated by Django 5.1.3 on 2025-01-09 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0002_alter_achievements_id_alter_chans_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solocassebrique',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
