# Generated by Django 5.1.4 on 2025-01-31 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0002_remove_multicassebrique_id_p2_remove_pong_id_p2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pong',
            name='score_p1',
        ),
        migrations.AddField(
            model_name='multicassebrique',
            name='id_p2',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='M_CB_games_as_p2', to='home_sys.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pong',
            name='id_p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_games_as_p2', to='home_sys.users'),
        ),
        migrations.AddField(
            model_name='pong',
            name='is_bot_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='multicassebrique',
            name='id_p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M_CB_games_as_p1', to='home_sys.users'),
        ),
        migrations.AlterField(
            model_name='pong',
            name='id_p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pong_games_as_p1', to='home_sys.users'),
        ),
    ]
