# Generated by Django 5.1.4 on 2025-02-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0002_multicassebrique_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='casse_brique_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
