# Generated by Django 5.1.4 on 2025-01-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0002_remove_maps_idmaps_alter_maps_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
