# Generated by Django 5.1.4 on 2025-02-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0002_alter_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='user_blocked', to='home_sys.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to='home_sys.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='friends_request',
            field=models.ManyToManyField(blank=True, related_name='user_friend_requests', to='home_sys.users'),
        ),
    ]
