# Generated by Django 5.1.4 on 2025-02-18 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0002_alter_messages_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOpenedChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=30)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_sys.users')),
            ],
        ),
    ]
