# Generated by Django 5.1.4 on 2025-01-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0003_alter_chans_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='idSender',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
