# Generated by Django 5.1.4 on 2025-02-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0003_casse_brique_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='casse_brique_room',
            name='map_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
