# Generated by Django 5.1.4 on 2025-01-31 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0003_remove_pong_score_p1_multicassebrique_id_p2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solocassebrique',
            name='id_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='S_CB_games', to='home_sys.users'),
        ),
    ]
