# Generated by Django 5.1.4 on 2025-01-14 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0003_alter_maps_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chans',
            name='created',
        ),
        migrations.AddField(
            model_name='chans',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
