# Generated by Django 5.1.4 on 2025-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0003_users_logstatus_users_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='pseudo',
            field=models.CharField(blank=True, default='pseudotest', max_length=30, null=True),
        ),
    ]
