# Generated by Django 5.1.4 on 2025-01-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0003_alter_privatechan_id_chan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=250),
        ),
    ]
