# Generated by Django 5.1.4 on 2025-02-14 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0003_messages_is_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='idTournaments',
        ),
        migrations.RemoveField(
            model_name='tournaments',
            name='nb_of_players',
        ),
        migrations.AlterField(
            model_name='matchstournaments',
            name='idMatchs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idMatchs', to='home_sys.pong'),
        ),
        migrations.AlterField(
            model_name='matchstournaments',
            name='idTournaments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idTournaments', to='home_sys.tournaments'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
