# Generated by Django 5.1.4 on 2025-01-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0004_messages_idsender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chans',
            name='private',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
