# Generated by Django 5.1.4 on 2025-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0004_alter_solocassebrique_id_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='pong',
            name='score_p1',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
