# Generated by Django 5.1.4 on 2025-02-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0004_remove_tournaments_idtournaments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='has_unread_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='invite',
            field=models.ManyToManyField(blank=True, related_name='user_invite', to='home_sys.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
