# Generated by Django 5.1.4 on 2025-01-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0004_remove_chans_created_chans_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField()),
                ('sender', models.CharField()),
                ('message', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
