# Generated by Django 5.1.4 on 2025-03-25 17:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0004_alter_users_name_alter_users_pseudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(primary_key=True), null=True, size=4),
        ),
    ]
