# Generated by Django 5.1.4 on 2025-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0005_tournaments_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='has_been_cut',
            field=models.BooleanField(default=False),
        ),
    ]
