# Generated by Django 5.1.4 on 2025-02-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0005_users_has_unread_notifications_users_invite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pong',
            name='color',
            field=models.CharField(default='yellow', max_length=50),
        ),
    ]
