# Generated by Django 5.1.4 on 2025-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0005_chans_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chans',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
