# Generated by Django 5.1.4 on 2025-02-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0006_pong_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='tournament_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
