# Generated by Django 5.1.4 on 2025-02-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sys', '0007_tournament_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
